### ISSUE TITLE
Cannot use 'connectionName' and 'connectionOptionsReaderOptions' options together

### ISSUE THREAD

**Issue by henri-hulski** [graphframework/graphstack#32]
Hi just start to explore typeorm and vesper. Really great frameworks.
Before I tried Prisma and graphql-yoga, but this is so much cleaner and easier to reason about!
One question, is it possible to use a different typeorm `connection` than `default` in vesper `bootstrap`?
Which was defined in `ormconfig.yml`.

**Comment by henri-hulski** [comment]
For example if I want to use the `dev` connection from the following configuration.
```yml
dev:
    type: "sqlite"
    database: "./todomvc.db"
    synchronize: true
    logging: false

test:
    type: "sqlite"
    database: "./test/test.db"
    synchronize: true
    logging: false
    dropSchema: true
```
